# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - typecheck
    - unused
linters-settings:
  gosec:
    excludes:
      - 'G115' # safe to exclude type conversion overflow checks in this repository since the integer values will always be low
