# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  branches:
    include:
      - master
      - release-*

variables:
  branch: $[ coalesce(variables['system.PullRequest.TargetBranch'], variables['build.SourceBranchName']) ]

pool:
  vmImage: ubuntu-20.04
container:
  image: golang:1.14.12-buster

steps:
  - checkout: self
    clean: true
    fetchDepth: 1
  - script: ci/scripts/install_tools.sh
    displayName: Install Tools

  - script: ci/scripts/lint.sh
    displayName: Vet and lint

  - script: go test -race ./...
    displayName: Run tests
