# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: fabric-chaincode-go

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: install Tools
        working-directory: ci/tools
        run: |
          go install golang.org/x/lint/golint
          go install golang.org/x/tools/cmd/goimports
      - name: Vet and lint
        run: ci/scripts/lint.sh
      - name: Run tests
        run: go test -race ./...

  build-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Staticcheck
        run: make staticcheck
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: v2
      - name: Unit test
        run: make unit-test
