# Copyright the Hyperledger Fabric contributors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: fabric-chaincode-go

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    - release-*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        clean: true
    - name: install Tools
      run: |
        pushd ci/tools
        go install golang.org/x/lint/golint
        go install golang.org/x/tools/cmd/goimports
        popd
    - name: Vet and lint
      run: ci/scripts/lint.sh
    - name: Run tests
      run: go test -race ./...
                    
