name: "Security vulnerability scan"

on:
  schedule:
    - cron: "27 3 * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - v1
          - v2
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - name: Scan
        run: make scan-${{ matrix.target }}
